#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 5299" \
        s6-setuidgid abc python3 /app/lazylibrarian/LazyLibrarian.py \
        --datadir /config --nolaunch
