#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/log \
    /config/cache

# copy config
if [[ ! -e /config/config.ini ]]; then
    cp /defaults/config.ini /config/config.ini
fi

# update version.txt
cp /defaults/version.txt /config/cache/version.txt

# permissions
lsiown abc:abc -R \
    /config
