#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /config/log \
    /config/cache \
    /downloads \
    /books

# copy config
if [[ ! -e /config/config.ini ]]; then
    cp /defaults/config.ini /config/config.ini
fi

# update version.txt
cp /defaults/version.txt /config/cache/version.txt

# permissions
lsiown -R abc:abc \
    /config

lsiown abc:abc \
    /downloads \
    /books
